### PR TITLE
[TGSRV-121] Fix hack for ExtendedData...

### PR DESCRIPTION
**Pull request by gevos**
...Move each ExtendedData section to the correct position.

### CODE REVIEW

**Comment by oterral** [comment]
Can you give an example of what was wrong with the previous code  please. it will help to review .

**Comment by gevos** [comment]
> Can you give an example of what was wrong with the previous code please. it will help to review .

You can find an example in the ticket, referenced in the commit message. Draw 3 lines in plan-editor and generate a kml by trying to save them.

**Comment by oterral** [comment]
yes but it's a react-spatial bug so if we can have a test case with react-spatial, it's better.  So everybody can test wihtout installing plan editor.

**Comment by edellucien** [comment]
I tested it in plan-editor and works to create correct KML for multiple lines. Good catch and thanks for fixing Eva! We will have to revert this temporary solution when ol will publish the fix :)

**Comment by oterral** [comment]
thx all

**Pull request merged**
