### PR TITLE
Lucien/sidebar menu item

### PR DESCRIPTION
**Pull request by edellucien**
Waiting on Sidebar created here: https://github.com/geops/react-spatial/pull/123

### CODE REVIEW

**Comment by oterral** [comment]
Nice, only one thing , when opening the text appears on top of the icons it's not really nice. Can you fix that with some css?

**Comment by oterral** [comment]
@lucien build failed

**Comment by edellucien** [comment]
You can squash all those 'conflict resolve' commit :smile:

**Comment by Lucien** [comment]
> @Lucien build failed

WHAT!?

**Pull request merged**
