### PR TITLE
Lucien/use stop api

### PR DESCRIPTION
**Pull request by edellucien**
# How to

Fix Use of Search with engines & apiKey prop
# Others

- [ ] It's not a hack or at least an unauthorized hack :).
- [ ] The images added are optimized.
- [ ] Everything in ticket description has been fixed.
- [ ] The author of the MR has made its own review before assigning the reviewer.
- [ ] IE11 tested.
- [ ] Labels applied. if it's a release? a hotfix?
- [ ] Tests added.

### CODE REVIEW

**Review by friedjoff — CHANGES_REQUESTED** [review]
Doesn't seem to use the StopAPI from mobility-toolbox-js anymore.

**Comment by edellucien** [comment]
In StopFinder we are loading:
`import { StopsAPI } from 'mobility-toolbox-js/api';`

**Review by danji90 — CHANGES_REQUESTED** [review]
@edellucien The requests in the rs-Demo now send requests with two key parameters (_apiKey_ and _key_)

**Comment by edellucien** [comment]
Thanks! Duplicates is created due to StopsAPI. I delete apiKey when from options passed to 'StopsAPI' to avoid this duplicate.

**Review by friedjoff — APPROVED** [review]

**Pull request merged**
