### PR TITLE
Update libs

### PR DESCRIPTION
**Pull request by oterral**

### CODE REVIEW

**Comment by candux** [comment]
After updating to mapbox-gl 1.9.0 I can't see any OL-Layers anymore. Do you see similiar behavior? If not, I can try to make a testcase.

**Comment by oterral** [comment]
We haven't enough tested , IE 11 is also broken :(

**Comment by oterral** [comment]
@candux  Probably this is the problem https://github.com/geops/react-spatial/pull/553/files

**Comment by candux** [comment]
> @candux Probably this is the problem https://github.com/geops/react-spatial/pull/553/files

Great. I will check it out maybe this evening

**Pull request merged**
